/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.weathertracker;

import static org.junit.jupiter.api.Assertions.assertTrue;

import com.amazonaws.services.lambda.runtime.Context;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class HandlerTest {
    private String appName;

    @Test
    void testHandleRequest() {
        Handler app = new Handler();
        Context context = Mockito.mock(Context.class);
        String result = app.handleRequest(context);
        assertTrue(result.startsWith("WeatherTracker"));
    }
}
