/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.weathertracker;

import com.amazonaws.services.lambda.runtime.Context;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
    }

    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Lambda handler method
     * @param context the Lambda request context
     * @return a string containing a message
     */
    public String handleRequest(Context context) {
        logger.info(getGreeting());
        return getGreeting();
    }
}
