/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.weathertracker;

import com.amazonaws.services.lambda.runtime.Context;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.weathertracker.controller.WeatherApiController;

public class Handler {
    private static final Logger LOG = LoggerFactory.getLogger(Handler.class);
    private static ConfigurableApplicationContext applicationContext;

    static {
        LOG.debug("Initializing Spring Boot application");
        try {
            applicationContext = SpringApplication.run(SpringAppForLambda.class);
        } catch (Exception e) {
            LOG.error("Error initializing Spring Boot application", e);
        }
    }

    /**
     * Lambda handler method
     * @param context the Lambda request context
     * @return a string containing a message
     */
    public String handleRequest(Context context) {
        MDC.put("awsRequestId", context.getAwsRequestId());
        LOG.info("Starting handleRequest()");
        WeatherApiController controller = applicationContext.getBean(WeatherApiController.class);
        try {
            controller.getWeather();
        } catch (Exception e) {
            LOG.error("Error getting weather", e);
            return "error";
        }
        LOG.info("Ending handleRequest()");
        return "ok";
    }

    public static void main(String[] args) {
        MDC.put("awsRequestId", "local:" + Thread.currentThread().getId());
        WeatherApiController controller = applicationContext.getBean(WeatherApiController.class);
        LOG.info("Starting main()");
        try {
            controller.getWeather();
        } catch (Exception e) {
            LOG.error("Error getting weather", e);
        }

        applicationContext.stop();
        LOG.info("Ending main()");
    }
}
